### ISSUE TITLE
Cannot import Tiler after installing the package

### ISSUE THREAD

**Issue by ADharaUTEXAS123007** [the-lay/tiler#5]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-a24a28623b2c> in <module>
      1 import numpy as np
----> 2 from tiler import Tiler, Merger

ModuleNotFoundError: No module named 'tiler'

**Comment by the-lay** [comment]
Huh, that's weird. Did you install it with pip or from source?

**Comment by arnabdhara** [comment]
(py37) bash-4.2$ pip install tiler
Collecting tiler
  Downloading tiler-0.3.1-py3-none-any.whl (20 kB)
Requirement already satisfied: numpy in /glb/hou/pt.sgs/data/ml_ai_us/4d/csoftware/miniconda3/envs/py37/lib/python3.7/site-packages (from tiler) (1.19.5)
Requirement already satisfied: tqdm in /glb/hou/pt.sgs/data/ml_ai_us/4d/csoftware/miniconda3/envs/py37/lib/python3.7/site-packages (from tiler) (4.61.1)
Installing collected packages: tiler
Successfully installed tiler-0.3.1

**Comment by the-lay** [comment]
Can't replicate, this seems to be a problem with configuration on your system.
```bash
(base) ~$ conda create --name tiler_test python=3.7
(base) ~$ conda activate tiler_test
(tiler_test) ~$ pip install tiler
(tiler_test) ~$ python
Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tiler import Tiler, Merger
>>> test = Tiler(data_shape=(100, 100), tile_shape=(10, 10))
>>> len(test)
100
```
